### ISSUE TITLE
EOFError: Ran out of input

### ISSUE THREAD

**Issue by lxfhfut** [koehlp/wda_tracker#1]
Hi Philipp,

First of all, thanks for the excellent work!

I have encountered an "EOFError: Ran out of input" when running the command "run_multi_cam_clustering.py  --config configs/clustering_configs/mta_es_abd_non_clean.py". This error was raised when calculating the pickled person_id_tracks. Below is the error message:

`Did not find pickled person_id_tracks. Calculating them now.
 36%|███▋      | 423/1165 [00:29<02:17,  5.40it/s]Ran out of input
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/lxfhfut/anaconda3/envs/wda/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/home/lxfhfut/Dropbox/PyCharm/wda_tracker/clustering/multi_cam_clustering.py", line 1413, in cluster_from_weights_task
    , dataset_type=dataset_type
  File "/home/lxfhfut/Dropbox/PyCharm/wda_tracker/clustering/multi_cam_clustering.py", line 1113, in cluster_from_weights
    ,dataset_type=dataset_type)
  File "/home/lxfhfut/Dropbox/PyCharm/wda_tracker/clustering/multi_cam_clustering.py", line 818, in cluster_tracks_via_hierarchical
    self.get_all_tracks_with_feature_mean(track_results_folder,dataset_type)
  File "/home/lxfhfut/Dropbox/PyCharm/wda_tracker/clustering/multi_cam_clustering.py", line 239, in get_all_tracks_with_feature_mean
    , dataset_type=dataset_type)
  File "/home/lxfhfut/Dropbox/PyCharm/wda_tracker/clustering/multi_cam_clustering.py", line 280, in calculate_track_feature_mean
    feature_dict = pickle.load(handle)
EOFError: Ran out of input
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/lxfhfut/Dropbox/PyCharm/wda_tracker/run_multi_cam_clustering.py", line 108, in <module>
    run_clustering.run()
  File "/home/lxfhfut/Dropbox/PyCharm/wda_tracker/run_multi_cam_clustering.py", line 84, in run
    , n_split_parts=self.cfg.cluster_from_weights.split_count
  File "/home/lxfhfut/Dropbox/PyCharm/wda_tracker/clustering/multi_cam_clustering.py", line 1377, in splitted_clustering_from_weights
    eval_results = get_async_tracking_results(eval_results)
  File "/home/lxfhfut/Dropbox/PyCharm/wda_tracker/clustering/multi_cam_clustering.py", line 1277, in get_async_tracking_results
    result = result.get()
  File "/home/lxfhfut/anaconda3/envs/wda/lib/python3.7/multiprocessing/pool.py", line 657, in get
    raise self._value
EOFError: Ran out of input
`
I checked the '*/work_dirs/clustering/config_runs/mta_es_abd_non_clean/person_id_tracks' folder, nothing was generated. 
Would you kindly help with this issue? Please let me know if you need further information to resolve the error. Thank you!

**Comment by koehlp** [comment]
Hi,
did you set up mmdetection?

**Comment by lxfhfut** [comment]
> Hi,
> did you set up mmdetection?

I think mmdetection has been set up properly because I successfully run the single camera tracker, which calls the person doctor in mmdetection.

**Comment by koehlp** [comment]
And did you also change all necessary paths in mta_es_abd_non_clean.py? I could provide you my config_runs/mta_es_abd_non_clean if required.

**Comment by lxfhfut** [comment]
> And did you also change all necessary paths in mta_es_abd_non_clean.py? I could provide you my config_runs/mta_es_abd_non_clean if required.

![Screenshot_2020-07-08_11-29-07](https://user-images.githubusercontent.com/3798812/86863478-97e08c80-c10e-11ea-9dfd-b5368caac0c6.png)

Thanks for your reply! I only worked on the 'MTA_ext_short' set coz running on the full-length videos is time-consuming.  I did change the config_runs/mta_es_abd_non_clean. Above is the screenshot, where
- work_dirs: I set it to the path to the 'work_dirs' folder I downloaded from the provided link of google drive.
- train_track_results_folder: I set it to the path of the single-camera tracking results on the training set of 'MTA_ext_short'.
- test_track_results_folder: I set it to the path of the single-camera tracking results on the test set of 'MTA_ext_short'.
- train_dataset_folder: I set it to the path of the training set of 'MTA_ext_short'.
- test_dataset_folder: I set it to the path of the test set of 'MTA_ext_short'.

![Screenshot from 2020-07-08 11-49-06](https://user-images.githubusercontent.com/3798812/86864760-18a08800-c111-11ea-9394-97efc8aba475.png)

The single-camera tracking works well (see above the screenshot of the generated single-camera tracking results) and I am able to run the evaluation on the results of single-camera tracking. I can also confirm that the 'reid_strong_baseline_config' and 'checkpoint_file' exist.
It would be most helpful if you could advise if the settings in config_runs/mta_es_abd_non_clean are correct or not. Thank you.

**Comment by koehlp** [comment]
It seems correct. Maybe some files in config_runs/mta_es_abd_non_clean are empty and you have to remove them and then you have to run the clustering again. I also tried to run it again and it seemed to work. Here is my folder:
https://studentkit-my.sharepoint.com/:u:/g/personal/utcyi_student_kit_edu/EdpWWQ93c-RFnlrmWFWQ2csBRF6iaswKMVmbGc0aq0BlBg?e=ZcqhLM

**Comment by lxfhfut** [comment]
> It seems correct. Maybe some files in config_runs/mta_es_abd_non_clean are empty and you have to remove them and then you have to run the clustering again. I also tried to run it again and it seemed to work. Here is my folder:
> https://studentkit-my.sharepoint.com/:u:/g/personal/utcyi_student_kit_edu/EdpWWQ93c-RFnlrmWFWQ2csBRF6iaswKMVmbGc0aq0BlBg?e=ZcqhLM

Hi Phillip,

The issue has been resolved by removing the config_runs/mta_es_abd_non_clean folder and running the clustering again. Thank you so much for your help!

**Comment by koehlp** [comment]
Your're welcome!
